/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.smt.training.sockets;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
